### ISSUE TITLE
Example is unavailable

### ISSUE THREAD

**Issue by TCMine** [DawnGroveStudios/GodotP2PNetwork#1]
The example link in the readme (https://github.com/DawnGroveStudios/GodotP2PNetworkExample) leads to a 404.

**Comment by Seann-Moser** [comment]
Sorry about that, this example project is still a work in progress. We will hopefully have it finished with in the next few days

**Comment by Seann-Moser** [comment]
Sorry for the delay, I have made this repo public. However, it is incomplete since I am spending most of my time on a different game. I will work on improving and adding more examples that repo in the coming weeks as well as improving the documentation.

**Comment by Seann-Moser** [comment]
https://github.com/DawnGroveStudios/GodotP2PNetworkExample/tree/main/basic

Closing out for now but please leave another issue if you would like to see a specific example or if you have any ideas to help improve this plugin in.
